### Criar produto
POST http://localhost:8080/produtos
Content-Type: application/json

{
  "nome": "UmaMusume 1",
  "precoAtual": 25.00
}

###

POST http://localhost:8080/produtos
Content-Type: application/json

{
  "nome": "Hololive",
  "precoAtual": 30.00
}

###

### Buscar por nome
GET http://localhost:8080/produtos/buscar?nome=UmaMusume

###
GET http://localhost:8080/produtos/buscar?nome=Hololive

###
GET http://localhost:8080/produtos?nome=UmaMusume&precoMax=40

###
POST http://localhost:8080/produtos
Content-Type: application/json

{
  "nome": "Oshi no Ko Vol 1",
  "precoAtual": 25.00
}

### Criar alerta
POST http://localhost:8080/alertas
Content-Type: application/json

{
  "nomeProduto": "Oshi no Ko",
  "precoMaximo": 30
}

###

### Listar alertas
GET http://localhost:8080/alertas

###
GET http://localhost:8080/scraping