### Criar produto
POST http://localhost:8080/produtos
Content-Type: application/json

{
  "nome": "Notebook Gamer",
  "url": "https://exemplo.com",
  "precoDesejado": 4500.00,
  "precoAtual": 5000.00,
  "tipo": "Eletronico",
  "ativo": true
}

### Listar produtos
GET http://localhost:8080/produtos